CREATE TABLE Entries (
    id       INT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
    `date`   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title    VARCHAR(100) NOT NULL,
    link     VARCHAR(200) NOT NULL,
    topic_id INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (topic_id) REFERENCES Topics (id) ON UPDATE CASCADE ON DELETE CASCADE
) engine=innodb; 